export const SET_NAME = "SET_NAME";
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'

export const OPEN_QUESTION_MODAL = "OPEN_QUESTION_MODAL";
export const CLOSE_QUESTION_MODAL = "CLOSE_QUESTION_MODAL";
export const CREATE_TRIVIA_QUESTION = "CREATE_TRIVIA_QUESTION";