//CREATE GAME
export const SET_TRIVIA_ID = "SET_TRIVIA_ID";
export const OPEN_QUESTION_MODAL = "OPEN_QUESTION_MODAL";
export const CLOSE_QUESTION_MODAL = "CLOSE_QUESTION_MODAL";
export const CREATE_TRIVIA_QUESTION = "CREATE_TRIVIA_QUESTION";
export const SET_NEW_QUESTION = "SET_NEW_QUESTION";
export const SET_EDITED_QUESTION = "SET_EDITED_QUESTION";
export const UNSET_QUESTIONS = "UNSET_QUESTIONS";

//USER
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";